# -*- coding: utf-8 -*-
"""Busca Tempo Medio de jogo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G93VssC41jAV2ZKiZ-xDl9cAz-GKKZ8e

# Busca Tempo Medio de jogo
Documentação da API: https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI
"""

# Instale a API: pip install howlongtobeatpy

from howlongtobeatpy import HowLongToBeat
import pandas as pd
from os import path
# import numpy as np



#from google.colab import drive

#drive.mount('/content/drive')

def gerarDataFrame():

  COLUNAS = ['Nome do jogo','Plataforma','Tempo médio','Tempo 100%','Tempo Gasto','Status','Nota',]
  
  planilha = pd.DataFrame(columns=COLUNAS)
  return planilha

def atualizarDataFrame(dir_arquivo):
    try:
      planilha = pd.read_csv(dir_arquivo, sep=',', encoding='UTF-8')
    except:
      print(f'Caminho invalido! {dir_arquivo}')
    return planilha

# Função busca jogo através da API how long to beat
def BuscaJogo(nome):
  jogos = None;
  while jogos is None:
    # Procura o jogo pelo nome e ignora caixa alta ou baixa
    jogos = HowLongToBeat().search(nome, similarity_case_sensitive=False);
    if jogos is None:
      print('Erro, nenhum jogo com este nome foi encontrado!');

  print('Jogos encontrados com este nome: ')
  for i in range(len(jogos)) :
    print(f'n°:{i}, {jogos[i].game_name}');
  numero = int(input("Informe o número do jogo que deseja escolher: "));
  if numero >= 0:
    jogo_escolhido = jogos[numero]
    print(f'Jogo escolhido: {jogo_escolhido.game_name}')
    return jogo_escolhido;
  else:
    return -1;

def buscaTempoMedioJogo(jogo_escolhido):
  return jogo_escolhido.main_story;

# Função para inserir jogo na tabela, chumbado para ir na primeira linha
def inserirJogo(jogo, planilha):
  indice = len(planilha)
  planilha.at[indice,'Nome do jogo'] = jogo.game_name
  planilha.at[indice,'Plataforma'] = input('Informe a plataforma em que se comprou o jogo: ')
  planilha.at[indice, 'Tempo médio'] = jogo.main_story
  planilha.at[indice, 'Tempo 100%'] = jogo.completionist
  planilha.at[indice, 'Tempo Gasto'] = float(input('Quanto tempo foi gasto no jogo?Ex: em 25 minutos: 0.25 ou em 2 horas e meia: 2.30 '))
  estado = input('Qual o estado do jogo? 1 - Em espera, 2 - Baixado, 3 - Zerado : ')
  match estado:
    case '1':
      estado = 'Em espera'
    case '2':
      estado = 'Baixado'
    case '3':
      estado = 'Zerado'
    case _:
      print('Erro, estado incorreto!')
      estado = 'Não informado'
  planilha.at[indice, 'Status'] = estado
  planilha.at[indice, 'Nota'] = int(input('Informe a Nota para o jogo, ou digite -1 caso ainda não queira informar: '))
  if planilha.at[indice, 'Nota'] == -1:
    planilha.at[indice, 'Nota'] = '';

# Menu
operacao = int(input('Olá, informe qual operação deseja realizar:\n1 - criar planilha do zero\n2 - atualizar planilha\n'))
dir = input('Informe o diretório da planilha, incluindo o nome dela e a estensão .csv')
match operacao:
  case 1:
    dir = path.join(dir, 'backlog.csv')
    dt = gerarDataFrame();
  case 2:
    dt = atualizarDataFrame(dir)
    # to-do: erro ao adicionar segunda linha, esta

jogo = BuscaJogo(input('Infome o nome do jogo: '))
inserirJogo(jogo, dt)

# Continuação do Menu
opc = 'Y'
opc = input('Deseja adicionar mais jogos? Y=Sim, N=Não')
while opc.upper() == 'Y':
  jogo = BuscaJogo(input('Infome o nome do jogo: '))
  if jogo != -1:
    inserirJogo(jogo, dt)
  opc = input('Deseja adicionar mais jogos? Y=Sim, N=Não')
else:
  print('Gerando o arquivo csv...')
  dt.to_csv(dir, header=True, index=False)
  print(f'Arquivo gerado em /{dir}')

# def deletarJogo(name):
#   for n in range(len(planilha)):
#     nomes = planilha.at[n, 'A']
#     # if name in nomes:
#     print(nomes)
# deletarJogo('Lollypop')

# Busca planilha com dados
# import gspread
# import pandas as pd
# from google.auth import default
# from google.colab import auth
# auth.authenticate_user()
# creds, _ = default()
# gc = gspread.authorize(creds)
# spreadsheet = gc.open_by_key('1zo9ngJRiM4LbjKnjvUFBID-rXQl1Nvx6MiBhLuxXLAE')
# worksheet = spreadsheet.get_worksheet(0)
# df = pd.DataFrame(worksheet.get("A1:A22"))
# Code for making the first row as header. Remove if not needed.
# df.columns = df.iloc[0]
# df = df.drop(0)
# df.head()

# lista = df['Jogo'].to_numpy();
# for i in lista:
#   jogo = BuscaJogo(i);
#   print(f'Tempo Médio: {jogo.main_story}\n Tempo para 100%: {jogo.completionist}');

